name: Remove branch deployments from GitHub Pages on branch deletion

# Ref https://docs.github.com/en/webhooks/webhook-events-and-payloads#delete

on:
  delete:

jobs:
  deploy:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - run: rm -r -- branch/${{ github.event.ref }}
      - run: git add -A
      - run: git commit -m "Pruning deleted '${{ github.event.ref }}' branch"
      - run: git push
