name: Deploy to GitHub Pages

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  deploy:
    if: github.event.deleted == false
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}


      - run: npm install
      - run: npm run build

      - run: git --version

      - name: Deploy
        uses: mark-poussard/actions-gh-pages@8d56e4159d1d222dbc12f6962b55456276ef002a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ github.ref != 'refs/heads/master' && format('branch/{0}', github.ref_name) || '' }}
          keep_target_files: env, branch
